Módulo: Bibliotecas e APIs (Python)<br>
Lista: NumPy 1<br>
Data: 08/2021<br>

In [1]:
# Importação da biblioteca NumPy
import numpy as np

**Q1:** Dado o array arr = np.arange(50), Selecione a alternativa INCORRETA na utilização de filtros e máscaras neste Numpy array.

In [2]:
arr = np.arange(50)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49])

In [3]:
len(arr)

50

Alternativas:

Abaixo, temos o uso incorreto de filtros e máscaras aplicados em um array, pois se está fazendo uma operação em cada elemento do array, a saber, o resto da divisão de cada elemento pelo número 2.

In [4]:
arr_atualizado = arr[arr % 2]
print(arr_atualizado)

[0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0
 1 0 1 0 1 0 1 0 1 0 1 0 1]


Abaixo, vemos usos adequados de filtros e máscaras sobre o array.

In [5]:
arr_atualizado = arr[arr > 5]
print(arr_atualizado)

[ 6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29
 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]


In [6]:
# Selecionamos os elementos maiores que 5
len(arr_atualizado)

44

In [7]:
arr_atualizado = arr[arr <= 10]
print(arr_atualizado)

[ 0  1  2  3  4  5  6  7  8  9 10]


In [8]:
# Selecionamos os elementos menores ou iguais a 10
len(arr_atualizado)

11

In [9]:
# Selecionamos os elementos que são diferentes de 1 ou de 3
arr_atualizado = arr[(arr != 1) | (arr != 3)]
print(arr_atualizado)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47
 48 49]


In [10]:
# Selecionamos os elementos que são diferentes de 1 ou de 3,
# o problema aqui é 3 se encaixa na condição != 1 e 1 se encaixa na condição !=3
len(arr_atualizado)

50

In [11]:
# Selecionamos os elementos que são diferentes de 1 ou de 3
arr_atualizado = arr[(arr != 1) & (arr != 3)]
print(arr_atualizado)

[ 0  2  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25
 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]


In [12]:
# Selecionamos os elementos que são diferentes de 1 e de 3
len(arr_atualizado)

48

**Q2:** Enunciado

Agora, vamos explorar os arrays aleatórios e máscaras. Faça o que se pede:

a) Crie um array aleatório de 15 itens entre 0 e 100;

b) Qual o maior número do array?

c) Qual a sua posição?

d) Verifique quais números do array são maior que 10;

e) Salve em uma nova lista apenas os itens entre 10 e 30.


In [13]:
array_a = np.random.randint(0, 100, 15)
print('a) Array aleatório 15 itens entre 0 e 100:',array_a)
print('b) O maior número do array é:',array_a.max())
print('c) A posição do maior número é:', array_a.argmax())
print('d) Números do array maior que 10:', array_a[array_a > 10])
lista_10a30 = array_a[(array_a >= 10) & (array_a < 30)]
print('e) Números entre 10 e 30:', lista_10a30)

a) Array aleatório 15 itens entre 0 e 100: [21 88 16 25 88 71 76 98 28 47 92 82 40 57 96]
b) O maior número do array é: 98
c) A posição do maior número é: 7
d) Números do array maior que 10: [21 88 16 25 88 71 76 98 28 47 92 82 40 57 96]
e) Números entre 10 e 30: [21 16 25 28]


**Q3:** Nosso próximo foco serão as matrizes. Faça o que se pede:

a) Gere uma matriz (3,2) com números linearmente espaçados entre 0 e 100 e intervalos de 20, usando o np.linspace();

b) Gere uma matriz aleatória (5,2) com números entre 0 e 100;

c) Crie um array com as dimensões apropriadas que, quando multiplicado pela matriz do item a), devolva essa mesma matriz. Use o método np.matmul().


In [14]:
# a)
matrizA = np.linspace(0,100, 6).reshape(3, 2)
matrizA

array([[  0.,  20.],
       [ 40.,  60.],
       [ 80., 100.]])

In [15]:
# b) Gere uma matriz aleatória (5,2) com números entre 0 e 100
matrizB = np.random.randint(0, 100, 10).reshape(5, 2) 
matrizB

array([[65, 66],
       [43, 55],
       [32, 43],
       [68, 81],
       [66,  5]])

In [16]:
# Crie um array com as dimensões apropriadas que
#, quando multiplicado pela matriz do item a), devolva essa mesma matriz. Use o método np.matmul().
matrizC = np.identity(2)
matrizC

array([[1., 0.],
       [0., 1.]])

In [17]:
matrizA @ matrizC

array([[  0.,  20.],
       [ 40.,  60.],
       [ 80., 100.]])

In [18]:
np.matmul(matrizA, matrizC)

array([[  0.,  20.],
       [ 40.,  60.],
       [ 80., 100.]])

In [19]:
matrizA

array([[  0.,  20.],
       [ 40.,  60.],
       [ 80., 100.]])

# Exercícios extras

1) Crie dois arrays de tamanho 5 com números aleatórios entre 0 e 100.

In [20]:
arr1 = np.random.randint(0, 100, 5)
arr2 = np.random.randint(0, 100, 5)
print(arr1) 
print(arr2)

[47 61 29 25 70]
[14 79 81 77 85]


2) Crie uma matriz de 2 linhas e 5 colunas a partir dos arrays do exercício anterior.

In [21]:
matriz = np.vstack([arr1, arr2])
matriz

array([[47, 61, 29, 25, 70],
       [14, 79, 81, 77, 85]])

In [22]:
matriz.ndim, matriz.shape

(2, (2, 5))

3) Exiba na tela o maior valor de cada linha, e depois de cada coluna da matriz do exercício 2.

In [24]:
# Maior valor de cada linha:
matriz.max(axis=1)

array([70, 85])

In [23]:
# Maior valor de cada coluna:
matriz.max(axis=0)

array([47, 79, 81, 77, 85])

4) Crie um array de tamanho 10 também com números aleatórios entre 0 e 100.

In [25]:
arr3 = np.random.randint(0, 100, 10)
arr3

array([24, 58, 83, 36, 42, 44, 22, 38, 46,  9])

5) Utilizando o reshape, crie uma matriz a partir do array anterior com as dimensões adequadas e calcule o produto matricial entre a matriz do exercício 2 e ela

In [26]:
arr3b = arr3.reshape(5, 2)
arr3b

array([[24, 58],
       [83, 36],
       [42, 44],
       [22, 38],
       [46,  9]])

In [27]:
produto = np.matmul(matriz, arr3b)
produto

array([[11179,  7778],
       [15899, 10911]])

6) Calcule o produto matricial entre o resultado do exercício 5 e a matriz identidade e exiba o resultado deste produto na tela.

In [28]:
np.matmul(produto, np.identity(2))

array([[11179.,  7778.],
       [15899., 10911.]])

7) Calcule o produto matricial entre a matriz do exercício 5 e a sua transposta.

In [29]:
np.matmul(arr3b, arr3b.T)

array([[3940, 4080, 3560, 2732, 1626],
       [4080, 8185, 5070, 3194, 4142],
       [3560, 5070, 3700, 2596, 2328],
       [2732, 3194, 2596, 1928, 1354],
       [1626, 4142, 2328, 1354, 2197]])

Extras:

In [30]:
# Usos do linspace
np.linspace((0, 1, 2), (10, 11, 12), num=10)

array([[ 0.        ,  1.        ,  2.        ],
       [ 1.11111111,  2.11111111,  3.11111111],
       [ 2.22222222,  3.22222222,  4.22222222],
       [ 3.33333333,  4.33333333,  5.33333333],
       [ 4.44444444,  5.44444444,  6.44444444],
       [ 5.55555556,  6.55555556,  7.55555556],
       [ 6.66666667,  7.66666667,  8.66666667],
       [ 7.77777778,  8.77777778,  9.77777778],
       [ 8.88888889,  9.88888889, 10.88888889],
       [10.        , 11.        , 12.        ]])

In [31]:
np.linspace([2.0, 1.], [3.0], num=5)

array([[2.  , 1.  ],
       [2.25, 1.5 ],
       [2.5 , 2.  ],
       [2.75, 2.5 ],
       [3.  , 3.  ]])

In [32]:
np.linspace([0, 100], [20], num=5)

array([[  0., 100.],
       [  5.,  80.],
       [ 10.,  60.],
       [ 15.,  40.],
       [ 20.,  20.]])