Módulo: Bibliotecas e APIs (Python)<br>
Lista: NumPy 2<br>
Data: 08/2021<br>

In [1]:
import numpy as np

**Q1:** Printe os elementos dos seguintes dois vetores usando apenas um for:

arr = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])

Depois, faça o mesmo usando numpy (usando a função nditer) e deixe um comentário sobre a diferença dos dois métodos.

In [2]:
# Criando o array
arr = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])
arr

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [3]:
# Analisando a dimensão e o shape do array arr:
arr.ndim, arr.shape

(3, (2, 2, 3))

In [4]:
# Print dos elementos do array arr: [[1,2,3], [4,5,6]] e [[7,8,9], [10,11,12]]
for element in arr: 
    print(element) 

[[1 2 3]
 [4 5 6]]
[[ 7  8  9]
 [10 11 12]]


In [5]:
# Para fazer um print dos elementos individuais, podemos usar "for" ou "nditer"
print("Com for:")
for i in range(arr.shape[0]):
    for j in range(arr.shape[1]):
        for k in range(arr.shape[2]):
            print(arr[i,j,k])
            
print("Com nditer:")
for x in np.nditer(arr):
    print(x)

Com for:
1
2
3
4
5
6
7
8
9
10
11
12
Com nditer:
1
2
3
4
5
6
7
8
9
10
11
12


O método nditer é otimizado para percorrer arrays e torna o código mais eficiente. Podemos ver que com o nditer apenas um for foi necessário. Se usarmos somente for, precisamos de 3 níveis para percorrer os elementos individuais.

**Q2:** Peça para o usuário uma lista com as comidas favoritas dele, depois transforme isso em um objeto numpy. Agora transformado, elimine todas as comidas que começam com uma vogal. Mostre o resultado.

Exemplo:

    Entrada: [maçã, uva, morango, melancia, acelga]

    Saída: [maçã, morango, melancia]

 

In [6]:
print("Informe suas comidas favoritas.\n\n")

comidas_favoritas = [] # Lista para armazenar as entradas inseridas
resposta = input("Digite uma comida favorita (digite 'fim' para encerrar): ")
while resposta != 'fim':
    comidas_favoritas.append(resposta)
    resposta = input("Digite uma comida favorita (digite 'fim' para encerrar): ")

# Transformar a lista de comidas em numpy array (facilita manipular strings)
comidas_favoritas = np.array(comidas_favoritas)

vogais = ['a', 'e', 'i', 'o', 'u'] # lista com as vogais

letras_iniciais = np.char.rjust(comidas_favoritas, 1) # seleciona só as letras iniciais
indices_para_excluir = np.where(np.in1d(letras_iniciais, vogais)) # índices onde as vogais são vistas
comidas_favoritas = np.delete(comidas_favoritas, indices_para_excluir) # deleta is itens do array

print(comidas_favoritas)

Informe suas comidas favoritas.


Digite uma comida favorita (digite 'fim' para encerrar): ameixa
Digite uma comida favorita (digite 'fim' para encerrar): maçã
Digite uma comida favorita (digite 'fim' para encerrar): uva
Digite uma comida favorita (digite 'fim' para encerrar): caqui
Digite uma comida favorita (digite 'fim' para encerrar): abacaxi
Digite uma comida favorita (digite 'fim' para encerrar): melão
Digite uma comida favorita (digite 'fim' para encerrar): mamão
Digite uma comida favorita (digite 'fim' para encerrar): fim
['maçã' 'caqui' 'melão' 'mamão']


**Q3:** Imprima a dimensão dos seguintes objetos numpy:

    a = np.array(2)

    b = np.array([1, 2, 3, 4, 5])

    c = np.array([[1, 2, 3], [4, 5, 6]])

    d = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])



In [7]:
objetos_numpy = [
    np.array(2),
    np.array([1, 2, 3, 4, 5]),
    np.array([[1, 2, 3],[4, 5, 6]]),
    np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])
]

for objeto_numpy in objetos_numpy:
    print('Array:\n', objeto_numpy)
    print('shape:', objeto_numpy.shape, '\n')

Array:
 2
shape: () 

Array:
 [1 2 3 4 5]
shape: (5,) 

Array:
 [[1 2 3]
 [4 5 6]]
shape: (2, 3) 

Array:
 [[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]
shape: (2, 2, 3) 



**Q4:** Transforme o array em uma matriz 4 por 3 utilizando numpy.

    arr = [1, 2, 3, 4, 'Amelia, 'Bruna, 'Carolina', 'Débora', True, False, False, True]

Depois, faça o mesmo para uma matriz 3 por 4.


In [8]:
arr = [1, 2, 3, 4, 'Amelia', 'Bruna', 'Carolina', 'Débora', True, False, False, True]
arr = np.array(arr)
arr

array(['1', '2', '3', '4', 'Amelia', 'Bruna', 'Carolina', 'Débora',
       'True', 'False', 'False', 'True'], dtype='<U11')

In [9]:
arr.reshape(4,3)

array([['1', '2', '3'],
       ['4', 'Amelia', 'Bruna'],
       ['Carolina', 'Débora', 'True'],
       ['False', 'False', 'True']], dtype='<U11')

In [10]:
arr.reshape(3,4)

array([['1', '2', '3', '4'],
       ['Amelia', 'Bruna', 'Carolina', 'Débora'],
       ['True', 'False', 'False', 'True']], dtype='<U11')

**Q5:** Transforme o seguinte array em uma matriz 3D 3x3x3:

    arr = range(27)

Deixe um comentário explicando o que significa uma matriz 3D.


In [11]:
arr = np.arange(27)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26])

In [12]:
arr.reshape(3,3,3)

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]]])

Uma matriz de 3 dimensões tem um nível adicional de aninhamento de elementos além do #nível de linhas e colunas. Da mesma forma que uma matriz (2D) é uma lista de linhas, uma matriz 3D é uma lista de matrizes. Pode imaginar como se fossem várias matrizes uma atrás da outra, cada uma constituindo uma camada de um cubo.

**Q6:** Tente transformar o seguinte array em uma matriz 3x3x3

    arr = [1, 2, 3, 4, 5, 6, 7, 8]

Funciona? Se sim, explique o motivo. Se não, explique o erro.


In [13]:
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8])
arr

array([1, 2, 3, 4, 5, 6, 7, 8])

arr.reshape(3,3,3) não funciona, pois não é possível organizar os 8 elementos em 3 linhas, 3 colunas e 3 elementos. A mensagem de erro diz: array de tamanho 8 não pode ser formatado em 3 x 3 x 3. 8 elementos podem ser agrupados em 2 linhas, 2 colunas e 2 elementos: arr2 = np.array(arr).reshape(2,2,2) <br>
Para arranjar em 3 x 3 x 3 são necessários 27 elementos.

In [14]:
arr.reshape(2,2,2).shape

(2, 2, 2)

**Q7:** Percorra o seguinte array utilizando for encaixado:

    arr = [[[1, 2], [3, 4]], [[5, 6], [7, 8]]]

Agora, percorra o mesmo array utilizando a função nditer de numpy.


In [15]:
arr = [[[1, 2], [3, 4]], [[5, 6], [7, 8]]]
arr = np.array(arr)
arr

array([[[1, 2],
        [3, 4]],

       [[5, 6],
        [7, 8]]])

In [16]:
print('Percorrendo arr usando somente for:')
for i in range(arr.shape[0]):
    for j in range(arr.shape[1]):
        for k in range(arr.shape[2]):
            print(arr[i, j, k])

print("Percorrendo arr usando nditer: ")
for x in np.nditer(arr):
    print(x)

Percorrendo arr usando somente for:
1
2
3
4
5
6
7
8
Percorrendo arr usando nditer: 
1
2
3
4
5
6
7
8


**Q8:** Percorra os indexes do seguinte array utilizando for encaixado:

    arr = [[[1, 2], [3, 4]], [[5, 6], [7, 8]]]

Agora faça o mesmo trabalho utilizando a função ndenumerate.


In [17]:
print("Percorrendo arr com for encaixado: ")
for i in range(arr.shape[0]):
    for j in range(arr.shape[1]):
        for k in range(arr.shape[2]):
            print(arr[i, j, k])

print("Percorrendo arr com np.ndenumerate: ")
for index, value in np.ndenumerate(arr):
    print(arr[index])

Percorrendo arr com for encaixado: 
1
2
3
4
5
6
7
8
Percorrendo arr com np.ndenumerate: 
1
2
3
4
5
6
7
8


**Q9:** Junte os dois seguintes arrays na horizontal:

    arr1 = [1, 2, 3]

    arr2 = [4, 5, 6]

Depois, os junte verticalmente.

In [18]:
arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])

In [19]:
# Juntando na horizontal
arr_h = np.hstack([arr1, arr2])
arr_h

array([1, 2, 3, 4, 5, 6])

In [20]:
# Juntando na vertical
arr_v = np.vstack([arr1, arr2])
arr_v

array([[1, 2, 3],
       [4, 5, 6]])

**Q10:** DESAFIO: Utilizando manipulação de arrays, ache os indexes do array cujo valor possua apenas 2 vogais no nome usando numpy.

frutas = ['banana', 'morango, 'uva', 'pitaia', 'abacate', 'abacaxi', 'acerola', 'jenipapo', 'kiwi']

In [21]:
frutas = np.array([
    'banana',
    'morango',
    'uva',
    'pitaia',
    'abacate',
    'abacaxi',
    'acerola',
    'jenipapo',
    'kiwi'
])

vogais = ['a', 'e', 'i', 'o', 'u']

contagens = sum([np.char.count(frutas, vogal) for vogal in vogais])
indices = np.where(contagens == 2)[0]

print(indices)

[2 8]


**Q11:** a) Tranforme o seguinte array 2D em dois arrays 2D:

    arr = [[1, 2], [3, 4], [5, 6], [7, 8]]

b) Transforme o seguinte array em três arrays com apenas uma coluna:

    arr = [[1, 2, 3], [4, 5, 6], [7, 8, 9]]

In [22]:
arr_a = np.array([[1, 2], [3, 4], [5, 6], [7, 8]])
print('Array original:')
print(arr_a)
print('Shape:',arr_a.shape)
print ('Array transformado:')
arr_a2 = arr.reshape(2,4)
print(arr_a2)
print('Shape:',arr_a2.shape)

Array original:
[[1 2]
 [3 4]
 [5 6]
 [7 8]]
Shape: (4, 2)
Array transformado:
[[1 2 3 4]
 [5 6 7 8]]
Shape: (2, 4)


In [23]:
arr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
arrays = np.hsplit(arr, 3)
print(arr)
print(arrays)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[array([[1],
       [4],
       [7]]), array([[2],
       [5],
       [8]]), array([[3],
       [6],
       [9]])]


In [24]:
for i in range(len(arrays)):
    print(f'Array {i}: \n', arrays[i])

Array 0: 
 [[1]
 [4]
 [7]]
Array 1: 
 [[2]
 [5]
 [8]]
Array 2: 
 [[3]
 [6]
 [9]]


**Q12:** **DESAFIO:** Utilizando manipulação de arrays, vamos seguir um conjunto de passos para organizar alguns dados. Teremos nesse seguinte array uma ordem que segue:

    [Nome do aluno, idade, 'gênero', signo, altura, nota do 1° semestre, nota do 2° bimestre, se está ou não inscrito no próximo ano da escola, nome do outro aluno, idade do outro aluno...]

    arr = ['Amélia', 13, 'F', 'peixes', 1.51, 9, 7, True, 'Bruno', 14, 'O', 'leão', 1.60, 4, 10, False, 'João', 14, 'M', 'escorpião', 1.58, 8, 9, True, 'Jordana', 13, 'F', 'escorpião', 1.72, 9, 9, False]

a) Enumere os indexes de todas as informações que são do tipo string.

b) Separe essas informações do objeto arr de forma que cada aluno tenha seu próprio array.

c) Separe em duas colunas, a primeira com o nome, a idade, o gênero e o signo e a segunda com a altura, nota do primeiro bimestre, nota do segundo bimestre e se está ou não inscrito no próximo ano.

d) Elimine o gênero de todos os arrays cujos alunos tem menos de 14 anos.


In [25]:
lista = ['Amélia', 13, 'F', 'peixes',
         1.51, 9, 7, True, 'Bruno', 
         14, 'O', 'leão', 1.60, 
         4, 10, False, 'João', 
         14, 'M', 'escorpião', 
         1.58, 8, 9, True, 
         'Jordana', 13, 'F', 
         'escorpião', 1.72, 9, 9, False]

In [26]:
arr = np.array(lista)
arr

array(['Amélia', '13', 'F', 'peixes', '1.51', '9', '7', 'True', 'Bruno',
       '14', 'O', 'leão', '1.6', '4', '10', 'False', 'João', '14', 'M',
       'escorpião', '1.58', '8', '9', 'True', 'Jordana', '13', 'F',
       'escorpião', '1.72', '9', '9', 'False'], dtype='<U32')

In [27]:
arr.ndim, arr.shape

(1, (32,))

In [28]:
#a) 
indices = np.where(np.char.isalpha(arr))[0]
print(indices)

[ 0  2  3  7  8 10 11 15 16 18 19 23 24 26 27 31]


In [29]:
# b)
alunos = np.split(arr,(4)) # separa o array dados em 4 arrays
print(alunos)

[array(['Amélia', '13', 'F', 'peixes', '1.51', '9', '7', 'True'],
      dtype='<U32'), array(['Bruno', '14', 'O', 'leão', '1.6', '4', '10', 'False'],
      dtype='<U32'), array(['João', '14', 'M', 'escorpião', '1.58', '8', '9', 'True'],
      dtype='<U32'), array(['Jordana', '13', 'F', 'escorpião', '1.72', '9', '9', 'False'],
      dtype='<U32')]


In [30]:
# c)
coluna1, coluna2 = np.hsplit(arr.reshape(-1, 8), 2)
print(coluna1)
print(coluna2)

[['Amélia' '13' 'F' 'peixes']
 ['Bruno' '14' 'O' 'leão']
 ['João' '14' 'M' 'escorpião']
 ['Jordana' '13' 'F' 'escorpião']]
[['1.51' '9' '7' 'True']
 ['1.6' '4' '10' 'False']
 ['1.58' '8' '9' 'True']
 ['1.72' '9' '9' 'False']]


In [31]:
# d)
def delete_gender(x):
    if int(x[1]) < 14:
        x[2] = None
    return x

sem_genero = np.apply_along_axis(delete_gender, axis=1, arr=coluna1)
print(sem_genero)

[['Amélia' '13' 'None' 'peixes']
 ['Bruno' '14' 'O' 'leão']
 ['João' '14' 'M' 'escorpião']
 ['Jordana' '13' 'None' 'escorpião']]
